openapi: 3.0.1
info:
  title: Claims API
  version: '1.0'
paths:
  /claims/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri: http://a8b99f8b693ee4ddabdb2a376caa10cd-1469786273.us-east-1.elb.amazonaws.com/claims/{id}
        httpMethod: GET
        type: http_proxy
        connectionType: INTERNET
        passthroughBehavior: WHEN_NO_MATCH
        requestParameters:
          integration.request.path.id: method.request.path.id
  /claims/{id}/summarize:
    post:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri: http://a8b99f8b693ee4ddabdb2a376caa10cd-1469786273.us-east-1.elb.amazonaws.com/claims/{id}/summarize
        httpMethod: POST
        type: http_proxy
        connectionType: INTERNET
        passthroughBehavior: WHEN_NO_MATCH
