apiVersion: v1
kind: Service
metadata:
  name: claims-api
  namespace: claims-dev
spec:
  type: LoadBalancer
  selector:
    app: claims-api
  ports:
    - port: 80
      targetPort: 8080
